# Generated by Django 5.1 on 2024-12-25 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_message_content_alter_message_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='subject',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
