# Generated by Django 5.2.8 on 2025-11-27 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_room_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='profile',
        ),
    ]
