# Generated by Django 6.0 on 2026-02-04 09:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_message_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='client_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('room', 'profile', 'client_id'), name='uniq_message_client_id_per_sender_room'),
        ),
    ]
